version: "2"
services:
  ws_server:
    build:
      context:    .
      dockerfile: Dockerfile
    image:          ws_server
    container_name: ws_server
    restart:        unless-stopped
    ports:
      - "33250:33250"
    environment:
      - TSServer=<TS Server IPv4>
      - WSServerPort=33250
